version: '3.8'

services:
  backend:
    build: ./API_kokoro-backend/kokoro-api-back
    container_name: kokoro-backend
    ports:
      - "8000:8000"
    volumes:
      - ./API_kokoro-backend/kokoro-api-back:/app

  frontend:
    build: ./kokoro-frontend
    container_name: kokoro-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
